version: '2.4'
services:
  web:
    build: .
    volumes:
      - .:/groceries
    tty: true
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - SECRET_KEY
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  db:
    image: postgres:11-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data: